fs = require 'fs'
path = require 'path'

{print} = require 'sys'
{spawn} = require 'child_process'

require.extensions['.glsl'] = (module, filename) ->
    glsl = fs.readFileSync filename, 'utf-8'
    module.exports = path.basename filename + ' = """' + glsl + '"""'

build = (callback) ->
    vertex =  require './src/vertex.glsl'
    fragment = require './src/fragment.glsl'

    glsl = spawn 'coffee', ['-e', vertex]
    glsl.stdout.on 'data', (data) ->
        console.log data.toString()

    coffee = spawn 'coffee', ['-c', '-o', 'lib', 'src']
    coffee.stdout.on 'data', (data) ->
        print data.toString()
    coffee.stderr.on 'data', (data) ->
        process.stderr.write data.toString()
    coffee.on 'exit', (code) ->
        callback?() if code is 0

task 'build', 'Build coffee including shader files with the .glsl extension.', ->
    build()
